apiVersion: v1
kind: ConfigMap
metadata:
  name: justice-gov-uk-demo
  namespace: justice-gov-uk-demo
data:
  WP_ENV: "production"
  WP_HOME: 'https://demo.justice.gov.uk'
  WP_SITEURL: 'https://demo.justice.gov.uk/wp'
  WP_LOOPBACK: 'http://localhost:8080'
  SENTRY_DEV_ID: '-demo'
  # See Azure Setup in the README for more information on how to get these values.
  # The following IDs are not private, they form part of the publicly visible oauth login url.
  OAUTH_CLIENT_ID: "3313c87a-399d-4130-a505-37c996721009"
  OAUTH_TENANT_ID: "c6874728-71e6-41fe-a9e1-2e8c36776ad8"
  # This is the version of the frontend that should be shown to users.
  # Show everyone version 2, regardless of the cookie.
  FRONTEND_VERSION_OVERRIDE: "2"
