apiVersion: v1
kind: ConfigMap
metadata:
  name: justice-gov-uk-demo
  namespace: justice-gov-uk-demo
data:
  WP_ENV: "production"
  WP_HOME: 'https://demo.justice.gov.uk'
  WP_SITEURL: 'https://demojustice.gov.uk/wp'
  SENTRY_DEV_ID: '-demo'
