apiVersion: v1
kind: ConfigMap
metadata:
  name: justice-gov-uk-config
data:
  WP_ENV: 'development'
  DB_HOST: 'mariadb'
  DB_NAME: 'justice'
  DB_USER: 'justice'
  DB_PASSWORD: 'justice'
  SENTRY_DEV_ID: '-damien-local-kube'
  GOV_NOTIFY_API_KEY: ''
  AUTH_KEY: 'strong-64-character-random-string'
  SECURE_AUTH_KEY: 'strong-64-character-random-string'
  LOGGED_IN_KEY: 'strong-64-character-random-string'
  NONCE_KEY: 'strong-64-character-random-string'
  AUTH_SALT: 'strong-64-character-random-string'
  SECURE_AUTH_SALT: 'strong-64-character-random-string'
  LOGGED_IN_SALT: 'strong-64-character-random-string'
  NONCE_SALT: 'strong-64-character-random-string'
